{
  description = "Development toolchain for home-k8s";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { nixpkgs, ... }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in
    {
      packages.${system}.libvirt-system-units = pkgs.runCommand "libvirt-system-units" { } ''
        mkdir -p "$out/lib/systemd/system"
        for unit in ${pkgs.libvirt}/lib/systemd/system/*; do
          ln -s "$unit" "$out/lib/systemd/system/$(basename "$unit")"
        done

        cat > "$out/lib/systemd/system/virtlogd.socket" <<'EOF'
        [Unit]
        Description=libvirt logging daemon socket

        [Socket]
        ListenStream=/run/libvirt/virtlogd-sock
        Service=virtlogd.service
        SocketMode=0600
        RemoveOnStop=yes

        [Install]
        WantedBy=sockets.target
        Also=virtlogd-admin.socket
        EOF

        cat > "$out/lib/systemd/system/virtlogd.service" <<'EOF'
        [Unit]
        Description=libvirt logging daemon
        BindsTo=virtlogd.socket
        After=virtlogd.socket

        [Service]
        Type=notify
        ExecStart=${pkgs.libvirt}/sbin/virtlogd --timeout 120
        Restart=on-failure
        EOF

        cat > "$out/lib/systemd/system/virtlockd.socket" <<'EOF'
        [Unit]
        Description=libvirt lock daemon socket

        [Socket]
        ListenStream=/run/libvirt/virtlockd-sock
        Service=virtlockd.service
        SocketMode=0600
        RemoveOnStop=yes

        [Install]
        WantedBy=sockets.target
        Also=virtlockd-admin.socket
        EOF

        cat > "$out/lib/systemd/system/virtlockd.service" <<'EOF'
        [Unit]
        Description=libvirt lock daemon
        BindsTo=virtlockd.socket
        After=virtlockd.socket

        [Service]
        Type=notify
        ExecStart=${pkgs.libvirt}/sbin/virtlockd --timeout 120
        Restart=on-failure
        EOF

        mkdir -p "$out/share/polkit-1/actions" "$out/share/polkit-1/rules.d"
        ln -s ${pkgs.libvirt}/share/polkit-1/actions/org.libvirt.unix.policy \
          "$out/share/polkit-1/actions/org.libvirt.unix.policy"
        ln -s ${pkgs.libvirt}/share/polkit-1/actions/org.libvirt.api.policy \
          "$out/share/polkit-1/actions/org.libvirt.api.policy"

        cat > "$out/share/polkit-1/rules.d/50-home-k8s-libvirt.rules" <<'EOF'
        polkit.addRule(function(action, subject) {
          if (action.id == "org.libvirt.unix.manage" && subject.user == "uta8a") {
            return polkit.Result.YES;
          }
        });
        EOF

        mkdir -p "$out/etc/libvirt"
        cat > "$out/etc/libvirt/qemu.conf" <<'EOF'
        # Generated by home-k8s; keeps libvirt on the pinned Nix QEMU build.
        default_emulator = "${pkgs.qemu}/bin/qemu-system-x86_64"
        EOF
      '';

      devShells.${system}.default = pkgs.mkShell {
        packages = with pkgs; [
          git
          curl
          cacert
          talosctl
          kubectl
          bitwarden-cli
          jq
          yq-go
          qemu
          OVMF
          libvirt
          virt-manager
        ];
      };
    };
}
