apiVersion: v1
kind: Namespace
metadata:
  name: linkding
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkding-pvc
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: data
              mountPath: /etc/linkding/data
          envFrom:
            - configMapRef: # TODO: secrets管理する
                name: envvar
---
apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: linkding
  annotations:
    tailscale.com/hostname: "linkding"
spec:
  selector:
    app: linkding
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-linkding-tailscale
  namespace: linkding
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - "linkding"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linkding
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
