name: Generate Infrastructure List

on:
  push:
    paths:
      - '**/readme.yaml'
      - '.github/workflows/generate-infra-list.yaml'
      - '.github/scripts/**'
    branches:
      - main

jobs:
  generate-list:
    name: Generate infrastructure list in README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Generate infrastructure table
        run: deno run --allow-read --allow-write .github/scripts/generate-readme.ts

      - name: Commit and push changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes to README.md"
            exit 0
          fi
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "docs: update infrastructure list in README.md"
          git push
